### PR TITLE
New plugin interface

### PR DESCRIPTION
**Pull request by jeanpierrefortune**

### CODE REVIEW

**Comment by odelcroi** [comment]
Should't we update the android example also?

**Comment by odelcroi** [comment]
Is there any unit tests that would make  sense ?

**Comment by jeanpierrefortune** [comment]
> Should't we update the android example also? BTW I'm surprised that the CI tests pass while android example apk shouldn't be compiling with this API update..

In fact, the main change is related to the plugin event and NFC plugins are not observable. That's why the build and the test is successful.

**Comment by jeanpierrefortune** [comment]
> Is there any unit tests that would make sense ?

Yes, we generally lack unit tests.

**Pull request merged**
